# Generated by Django 3.2.8 on 2024-03-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='pic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
